#!/usr/bin/python
"""go
   runs ioflo plan from command line shell

"""
#imports
import exceptions
import pdb
import cProfile
import pstats
import sys
import os
import getopt
import string
import types
import time
import struct


debug = True
#debug = False


if __name__ == "__main__":

    if debug:
        sys.stderr.write("go arguments:\n")
        sys.stderr.write(str(sys.argv) + "\n") #joins list items with space separator

    filename = '../plan/box1.haf'
    period = 0.125
    verbose = 2
    real = False

    usage = "python go -f filename -p period -v level -r -h\n"


    try:
        (opts, pargs) = getopt.getopt(sys.argv[1:], "hrv:f:p:") #format 
    except getopt.GetoptError, e:
        #print help info and exit
        if debug:
            sys.stderr.write("Error processin %s" % str(sys.argv)) #joins list items with space separator
            sys.stderr.write("Usage: %s" % usage) #joins list items with space separator

        sys.exit(2)


    if debug:
        sys.stderr.write("go options parsed:\n")
        sys.stderr.write(str(opts) + "\n") #joins list items with space separator

    help = False

    for x in opts:
        if x[0] == '-f':  
            filename = x[1]
        if x[0] == '-p':
            period = float(x[1])
        if x[0] == '-v':
            verbose = int(x[1])
        if x[0] == '-r':
            real = True
        if x[0] == '-h':
            sys.stderr.write(usage)
            help = True

    if not help:
        if debug:
            sys.stderr.write("fileName = %s, period = %0.3f verbose = %d real = %s \n" %\
                             (filename, period, verbose, real))

        print sys.path

        # absolute import since command line
        from haf.app.run import Run

        Run(fileName = filename, period = period, 
            verbose = verbose, real = real)

