#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
ioflo CLI

Runs ioflo plan from command line shell

example:

ioflo -v concise -r -n autoscale -p 0.0625 -f autoscale.flo -b autoscaling


"""
import sys
import ioflo.app.run

def main():
    """ Main entry point for ioflo CLI"""
    args = ioflo.app.run.parseArgs()

    ioflo.app.run.run(  name=args.name,
                        period=float(args.period),
                        real=args.realtime,
                        retro=args.retrograde,
                        filepath=args.filename,
                        behaviors=args.behaviors,
                        mode=args.parsemode,
                        username=args.username,
                        password=args.password,
                        verbose=args.verbose,
                        consolepath=args.console,
                        statistics=args.statistics)

if __name__ == '__main__':
    main()
